twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig','@FOSCKEditor/Form/ckeditor_widget.html.twig',
                  'Form/Type/autocomplete.html.twig',
                  'Form/Type/autoentity.html.twig',
                  'Form/Type/Jdate.html.twig']
    globals:
        UserMGR: "@UserMGR"
        EntityMGR:  "@EntityMGR"
        Jdate:  "@Jdate"
        ConfigMGR:  "@ConfigMGR"
